<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <PackageId>Carried.Idempotency.EntityFrameworkCore</PackageId>
        <Authors>Carried</Authors>
        <Description>
            Entity Framework Core relational provider for Carried.Idempotency.
        </Description>

        <PackageTags>idempotency;entityframeworkcore;efcore;dotnet;database</PackageTags>

        <PackageProjectUrl>https://github.com/Carried520/Carried.Idempotency</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Carried520/Carried.Idempotency</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"
                          Version="10.0.11"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Carried.Idempotency.DependencyInjection\Carried.Idempotency.DependencyInjection.csproj"/>
        <ProjectReference Include="..\Carried.Idempotency\Carried.Idempotency.csproj"/>
    </ItemGroup>

</Project>