<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <PackageId>Carried.Idempotency.DependencyInjection</PackageId>
        <Authors>Carried</Authors>
        <Description>
            Dependency injection infrastructure for configuring Carried.Idempotency providers.
        </Description>

        <PackageTags>idempotency;dependency-injection;dotnet</PackageTags>

        <PackageProjectUrl>https://github.com/Carried520/Carried.Idempotency</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Carried520/Carried.Idempotency</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Carried.Idempotency\Carried.Idempotency.csproj" />
    </ItemGroup>

</Project>